Create activities OT118-235
alkemyTech/OT118-Server pull request #1
Opened 2021-12-17 03:51 UTC by emmanueltabares

endpoint post/Activities

2021-12-17 23:07 UTC, manuelfrancisco requested changes

2021-12-17 23:07 UTC, manuelfrancisco commented on controllers/activities.js
> +        const { name } = req.body;
Estas constantes no las incluiría, le pasaría el `req.body` directamente al service.create

2021-12-17 23:07 UTC, manuelfrancisco commented on controllers/activities.js
> +        if(name && content) {
Estas validaciones van en un middleware, recordá que acordamos usar express-validator

2021-12-17 23:07 UTC, manuelfrancisco commented on controllers/activities.js
> +            await activitiesService.create(data);
Como dije antes le enviaría el `req.body` directamente por parámetro. Y devolvería lo que devuelve el service (que viene desde el repository).

2021-12-17 23:07 UTC, manuelfrancisco commented on package.json
> +    "express-fileupload": "^1.2.1",
Esta dependencia sacala y donde se utilice comentalo porfa

2021-12-17 23:07 UTC, manuelfrancisco commented on repositories/activities.js
> +    await db.Activities.create(data);
Hacer el return del método awaiteado

2021-12-17 23:07 UTC, manuelfrancisco commented on services/activities.js
> +    await activitiesRepository.create(data);
Acá también hacer el return

2021-12-20 22:36 UTC, emmanueltabares commented on controllers/activities.js
> +        if(name && content) {
Se creó un middleware

2021-12-21 12:02 UTC, manuelfrancisco requested changes

2021-12-21 12:02 UTC, manuelfrancisco commented on routes/activities.js
> +    authMiddleware.isAuth,
Si usa el middleware isAdmin, el de isAuth está de más

2021-12-21 12:02 UTC, manuelfrancisco commented on controllers/activities.js
> +        const newActivitie = await activitiesService.create(req.body);
El singular de activities es activity

2021-12-21 12:02 UTC, manuelfrancisco commented on controllers/activities.js
> +            msg: `Activitie created succesfully`,
El singular de activities es activity

2021-12-21 12:02 UTC, manuelfrancisco commented on repositories/activities.js
> +    const newActivitie = await db.Activities.create(data);
Acá se puede hacer return directamente

2021-12-21 12:02 UTC, manuelfrancisco commented on services/activities.js
> +    const newActivitie = await activitiesRepository.create(data);
Acá se puede hacer un return directamente

2021-12-21 21:23 UTC, manuelfrancisco submitted a review, later dismissed

2021-12-21 22:51 UTC, manuelfrancisco submitted a review, later dismissed

2021-12-21 23:50 UTC, manuelfrancisco approved these changes

2021-12-21 23:50 UTC, merged