endpoint ownership OTT118-220
alkemyTech/OT118-Server pull request #18
Opened 2021-12-21 05:24 UTC by Emiliobau

2021-12-21 14:58 UTC, manuelfrancisco requested changes

2021-12-21 14:58 UTC, manuelfrancisco commented on middlewares/auth.js
> +const auth = require('../module/auth'); //esto lo tiene que hacer Adrian en este archivo va a estar
Porfa sacá todos los comentarios, a menos de que sean estrictamente necesarios no ponemos comentarios, para eso hacemos que los nombres de variables y funciones sean bien representativos de para qué sirven

2021-12-21 14:58 UTC, manuelfrancisco commented on middlewares/auth.js
> +  if( userBdRoleId === 1){     // el roleId = 1 es el rol de administrador
El rol de administrador habría que ir a buscarlo a la base por nombre para no tener el Id hardcodeado

2021-12-21 14:58 UTC, manuelfrancisco commented on middlewares/auth.js
> +const inOwnershipUser = async (req, res, next) => {
El nombre preferible que sea isOwnUser

2021-12-22 03:57 UTC, Emiliobau commented on middlewares/auth.js
> +  if( userBdRoleId === 1){     // el roleId = 1 es el rol de administrador
esto no me doy cuenta como hacerlo ??? si me podes explicar un poco mas como seria se agradece!! no seria lo mismo tener hardcodeado el nombre que tener hardcodeado el id ??? perdon soy muy nuevo en esto

2021-12-30 22:39 UTC, manuelfrancisco approved these changes

2021-12-30 22:46 UTC, merged