endpoint PATCH activities/:id
alkemyTech/OT118-Server pull request #24
Opened 2021-12-26 02:00 UTC by emmanueltabares

2021-12-29 13:00 UTC, manuelfrancisco requested changes

2021-12-29 13:00 UTC, manuelfrancisco commented on routes/activities.js
> +router.patch('/:id', authMiddleware.isAdmin, activitiesController.update)
En la tarea especifica que tiene que ser un PUT y no un PATCH

2021-12-29 13:00 UTC, manuelfrancisco commented on services/activities.js
> +    const updateActivity = await activitiesRepository.update(id, body);
Antes del update convendría validar que la activity exista, y si no existe levantar un error

2021-12-29 21:36 UTC, emmanueltabares commented on services/activities.js
> +    const updateActivity = await activitiesRepository.update(id, body);
Ese filtro esta en el controller. Lo saco y lo pongo en el service?

2021-12-30 00:36 UTC, manuelfrancisco requested changes

2021-12-30 00:36 UTC, manuelfrancisco commented on services/activities.js
> +    const updateActivity = await activitiesRepository.update(id, body);
Sí, esa es una validación de negocio y pertenece al servicio

2021-12-30 22:40 UTC, manuelfrancisco approved these changes

2021-12-30 22:46 UTC, merged