Finished remove users
alkemyTech/OT118-Server pull request #41
Opened 2021-12-29 11:34 UTC by Robertlean

OT118-219 Remove users

2022-01-04 01:13 UTC, Robertlean reviewed
Arreglos 219

2022-01-05 22:18 UTC, Robertlean reviewed
Review please

2022-01-05 22:48 UTC, manuelfrancisco requested changes

2022-01-05 22:48 UTC, manuelfrancisco commented on routes/index.js
> +const usersRouter = require('./users')
Se están incluyendo las rutas 2 veces

2022-01-05 22:48 UTC, manuelfrancisco commented on routes/users.js
> +router.delete('/:id', authMiddleware.isAuth,authMiddleware.inOwnUser, usersController.remove);
Usá sólo el middleware isOwnUser

2022-01-05 22:48 UTC, manuelfrancisco commented on services/users.js
> +const getProfile = async (id) => {
Está repetido el getProfile

2022-01-05 23:17 UTC, Robertlean commented on routes/index.js
> +const usersRouter = require('./users')
arreglado

2022-01-05 23:17 UTC, Robertlean commented on routes/users.js
> +router.delete('/:id', authMiddleware.isAuth,authMiddleware.inOwnUser, usersController.remove);
arreglado

2022-01-05 23:17 UTC, Robertlean commented on services/users.js
> +const getProfile = async (id) => {
arreglado

2022-01-07 14:11 UTC, manuelfrancisco approved these changes

2022-01-07 14:14 UTC, merged