Ot118 229 fix
alkemyTech/OT118-Server pull request #61
Opened 2022-01-06 16:30 UTC by YTDcontrol

Please review this update categories to return item updated content instead of update result.

2022-01-06 22:11 UTC, manuelfrancisco requested changes

2022-01-06 22:11 UTC, manuelfrancisco commented on services/categories.js
> +    res.status(404).json({ msg: 'Category does not exists' });
esto debería hacerse desde otro lugar, no tengo claro cómo decidieron hacerlo pero el concepto de pasar la res para que la maneje el service está mal

2022-01-06 22:25 UTC, YTDcontrol commented on services/categories.js
> +    res.status(404).json({ msg: 'Category does not exists' });
Al dia de hoy decidimos enviarlos con el manejador de errores de app.js.

2022-01-07 20:57 UTC, manuelfrancisco approved these changes

2022-01-07 20:57 UTC, merged