middleware validaition users 213
alkemyTech/OT118-Server pull request #8
Opened 2021-12-20 00:23 UTC by Robertlean

2021-12-28 12:21 UTC, manuelfrancisco requested changes

2021-12-28 12:21 UTC, manuelfrancisco commented on middlewares/auth.js
> +    const error = new Error('No Token provied');
En los middlewares tenés que editar ya la respuesta, fijate en otros middlewares ya hechos

2021-12-30 00:19 UTC, manuelfrancisco approved these changes, later dismissed

2021-12-30 00:27 UTC, manuelfrancisco requested changes

2021-12-30 00:27 UTC, manuelfrancisco commented on middlewares/auth.js
> +const jwt = require('jsonwebtoken')
Para qué incluís jwt acá? No deberías

2021-12-30 00:27 UTC, manuelfrancisco commented on middlewares/auth.js
> +      return res.status(404).json({
Las respuestas son como en los controllers, no hay que hacer return, simplemente hacer res.status(blabla

2021-12-30 22:14 UTC, Robertlean commented on middlewares/auth.js
> +    const error = new Error('No Token provied');
correction

2021-12-30 22:15 UTC, Robertlean commented on middlewares/auth.js
> +const jwt = require('jsonwebtoken')
correction

2021-12-30 22:15 UTC, Robertlean commented on middlewares/auth.js
> +      return res.status(404).json({
correction

2021-12-30 22:40 UTC, manuelfrancisco approved these changes

2021-12-30 22:46 UTC, merged